name: Telegram Bot Service

on:
  push:
    branches: [ main, master ]
  workflow_dispatch:
    inputs:
      restart:
        description: 'Restart bot service'
        required: false
        default: 'false'

jobs:
  deploy-bot:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Set up Python 3.11
      uses: actions/setup-python@v4
      with:
        python-version: '3.11.9'
    
    - name: Cache pip dependencies
      uses: actions/cache@v3
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
    
    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y gcc g++
    
    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip setuptools wheel
        pip install --only-binary=:all: --no-build-isolation -r requirements.txt
    
    - name: Run Telegram Bot
      env:
        BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
        SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
        SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}
        ADMIN_ID: ${{ secrets.ADMIN_ID }}
        CONTRACT_ADDRESS: ${{ secrets.CONTRACT_ADDRESS }}
        ADMIN_PRIVATE_KEY: ${{ secrets.ADMIN_PRIVATE_KEY }}
        ADMIN_ADDRESS: ${{ secrets.ADMIN_ADDRESS }}
        BSC_NODE_URL: ${{ secrets.BSC_NODE_URL }}
      run: |
        echo "🚀 Starting Telegram Bot..."
        python bot.py
